import React from "react";
const columns = [
  {name: "ID", uid: "id", sortable: true},
  {name: "Nombre", uid: "name", sortable: true},
  {name: "Apellido", uid: "lastname", sortable: true},
  {name: "Email", uid: "email"},
  {name: "Celular", uid: "phone"},
  {name: "Estado", uid: "status", sortable: true},
  {name: "Acciones", uid: "actions"},
];

const statusOptions = [
  {name: "Active", uid: "active"},
  {name: "Inactive", uid: "inactive"},
];

const users = [
  {
    id: 1,
    name: "Tony",
    lastname: "Reichert",
    phone: 12345,
    status: "active",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "Zoey",
    lastname: "Lang",
    phone: 12345,
    status: "inactive",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    name: "Jane",
    lastname: "Fisher",
    phone: 12345,
    status: "active",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    name: "William",
    lastname: "Howard",
    phone: 12345,
    status: "active",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    name: "Kristen",
    lastname: "Copper",
    phone: 12345,
    status: "active",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    name: "Brian",
    lastname: "Kim",
    phone: 12345,
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "brian.kim@example.com",
    status: "active",
  },
  {
    id: 7,
    name: "Michael",
    lastname: "Hunt",
    phone: 12345,
    status: "inactive",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    email: "michael.hunt@example.com",
  },
  {
    id: 8,
    name: "Samantha",
    lastname: "Brooks",
    phone: 12345,
    status: "active",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    email: "samantha.brooks@example.com",
  },
  {
    id: 9,
    name: "Frank",
    lastname: "Harrison",
    phone: 12345,
    status: "inactive",
    avatar: "https://i.pravatar.cc/150?img=4",
    email: "frank.harrison@example.com",
  },
  {
    id: 10,
    name: "Tony",
    lastname: "Reichert",
    phone: 12345,
    status: "active",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 11,
    name: "Zoey",
    lastname: "Lang",
    phone: 12345,
    status: "inactive",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 12,
    name: "Jane",
    lastname: "Fisher",
    phone: 12345,
    status: "active",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 13,
    name: "William",
    phone: 12345,
    lastname: "Howard",
    status: "active",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 14,
    name: "Kristen",
    phone: 12345,
    lastname: "Copper",
    status: "active",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 15,
    name: "Brian",
    phone: 12345,
    lastname: "Kim",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "brian.kim@example.com",
    status: "active",
  },
  {
    id: 16,
    name: "Michael",
    phone: 12345,
    lastname: "Hunt",
    status: "inactive",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    email: "michael.hunt@example.com",
  },
  {
    id: 17,
    name: "Samantha",
    phone: 12345,
    lastname: "Brooks",
    status: "active",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    email: "samantha.brooks@example.com",
  },
  {
    id: 18,
    name: "Frank",
    lastname: "Harrison",
    phone: 12345,
    status: "inactive",
    avatar: "https://i.pravatar.cc/150?img=4",
    email: "frank.harrison@example.com",
  },
];

export {columns, users, statusOptions};