"use client";
import "./globals.css";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./redux/provider";
import { usePathname } from "next/navigation";
import { deleteUser } from "./redux/features/userSlice";
import { useAppDispatch } from "./redux/hooks";
import { GoogleMap, LoadScript } from "@react-google-maps/api";
import GOOGLE_MAPS_API_KEY from "@/googleMapsConfig";

import {
  Navbar,
  NavbarBrand,
  NavbarContent,
  NavbarItem,
  NavbarMenuToggle,
  NavbarMenu,
  NavbarMenuItem,
  Link,
  Button,
  Avatar,
  AvatarIcon,
  Dropdown,
  DropdownTrigger,
  DropdownMenu,
  DropdownSection,
  DropdownItem,
} from "@nextui-org/react";



const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const rol = typeof window !== 'undefined' ? JSON.parse(localStorage.getItem("rol") || "0") as number : 0;
  const router = useRouter();

  if (pathname === "/Login") {
    return (
      <Providers>
        <body className=" h-screen w-screen">
          <div className="h-full flex flex-col">{children}</div>
        </body>
      </Providers>
    );
  }
  
 // console.log("rol", rol);

  const menuItems = [
    "Profile",
    "Dashboard",
    "Activity",
    "Analytics",
    "System",
    "Deployments",
    "My Settings",
    "Team Settings",
    "Help & Feedback",
    "Log Out",
  ];
  
  const handleMyPerfil = () => {
    router.push("/Usuario/MiPerfil");
  };
  const handleCambiarContrasena = () => {
    router.push("/Usuario/UpdatePassword");
  };
  const handleProductores = () => {
    router.push("/Productor/Mostrar");
  };
  const handleCerrarSesion = () => {
    // dispatch(deleteUser());
    router.push("/Login");
  };
  const handleProductos = () => {
    router.push("/Producto/Mostrar");
  };
  const handleCategorias = () => {
    router.push("/Categoria/Mostrar");
  };

  const handleOrganizaciones = () => {
    router.push("/Organizacion/Mostrar");
  };
  const handleInsumos = () => { 
    router.push("/Insumo/Mostrar");
  };
  const handleProveedores = () => {
    router.push("/Proveedor/Mostrar");
  };
  const handleProduccion = () => {
    router.push("/Produccion/Mostrar");
  };

  const handleDetalles = () => {
    router.push("/DetallesVenta/");
  };
  
  return (
    <html lang="en" className="">
      <body className="bg-white h-screen w-screen">
        <div className="h-full w-full flex flex-col">
          <Providers>
            <Navbar
              isBordered
              isMenuOpen={isMenuOpen}
              onMenuOpenChange={setIsMenuOpen}
            >
              <NavbarContent className="sm:hidden" justify="start">
                <NavbarMenuToggle
                  aria-label={isMenuOpen ? "Close menu" : "Open menu"}
                />
              </NavbarContent>
              <NavbarContent className="sm:hidden pr-3" justify="center">
                <NavbarBrand>
                  <p className="font-bold text-xl  text-lime-400 ">PYMES</p>
                </NavbarBrand>
              </NavbarContent>

              <NavbarContent className="hidden sm:flex gap-4" justify="center">
                <NavbarBrand>
                  <p className="font-bold text-xl text-lime-400 ">PYMES</p>
                </NavbarBrand>
                {rol === 0 && (
                  <NavbarItem>
                    <Link
                      color="foreground"
                      onClick={handleOrganizaciones}
                      aria-current="page" className="cursor-pointer"
                    >
                      Organizaciones
                    </Link>
                  </NavbarItem>
                )}
                {rol === 1 && (
                   <NavbarItem>
                   <Link
                     color="foreground"
                     onClick={handleProductores}
                     aria-current="page" className="cursor-pointer"
                   >
                     Productores
                   </Link>
                 </NavbarItem>
                )}
                
                {rol === 2 && (
                   <NavbarItem>
                   <Link
                     color="foreground"
                     onClick={handleProductos}
                     aria-current="page" className="cursor-pointer"
                   >
                     Productos
                   </Link>
                 </NavbarItem>
                )}
                  {rol === 2 && (
                   <NavbarItem>
                   <Link
                     color="foreground"
                     onClick={handleProduccion}
                     aria-current="page" className="cursor-pointer"
                   >
                     Producción
                   </Link>
                 </NavbarItem>
                )}
                {rol === 2 && (
                   <NavbarItem>
                   <Link
                     color="foreground"
                     onClick={handleCategorias}
                     aria-current="page" className="cursor-pointer"
                   >
                     Categorias
                   </Link>
                 </NavbarItem>
                )}
                {rol === 2 && (
                   <NavbarItem>
                   <Link
                     color="foreground"
                     onClick={handleInsumos}
                     aria-current="page" className="cursor-pointer"
                   >
                     Insumos
                   </Link>
                 </NavbarItem>
                )}
                {rol === 2 && (
                   <NavbarItem>
                   <Link
                     color="foreground"
                     onClick={handleProveedores}
                     aria-current="page" className="cursor-pointer"
                   >
                     Proveedores
                   </Link>
                 </NavbarItem>
                )}
                 {rol === 2 && (
                   <NavbarItem>
                   <Link
                     color="foreground"
                     onClick={handleDetalles}
                     aria-current="page" className="cursor-pointer"
                   >
                     Ventas 
                   </Link>
                 </NavbarItem>
                )}
              
              
                
              </NavbarContent>

              <NavbarContent justify="end">
                
              
                <NavbarItem>
                  <Dropdown>
                    <DropdownTrigger>
                      <Avatar
                        as={Link}
                        icon={<AvatarIcon />}
                        classNames={{
                          base: "bg-gradient-to-br from-[#FFB457] to-[#FF705B]",
                          icon: "text-black/80",
                        }}
                      />
                    </DropdownTrigger>
                    <DropdownMenu aria-label="Static Actions">
                      <DropdownItem key="miPerfil">
                        <Link
                          className=" w-full"
                          onClick={handleMyPerfil}
                        >
                          Mi Perfil
                        </Link>
                      </DropdownItem>
                      <DropdownItem key="cambiarContraseña">
                        <Link
                          className=" w-full"
                          onClick={handleCambiarContrasena}
                        >
                          Cambiar Contraseña
                        </Link>
                      </DropdownItem>
                      <DropdownItem
                        key="delete"
                        className="text-white"
                        color="danger"
                      >
                        <Link
                          className="text-danger w-full hover:text-white"
                          color="danger"
                          onClick={handleCerrarSesion}
                        >
                          Cerrar Sesión
                        </Link>
                      </DropdownItem>
                    </DropdownMenu>
                  </Dropdown>
                </NavbarItem>
              </NavbarContent>

              <NavbarMenu>
                {menuItems.map((item, index) => (
                  <NavbarMenuItem key={`${item}-${index}`}>
                    <Link
                      className="w-full"
                      color={
                        index === 2
                          ? "warning"
                          : index === menuItems.length - 1
                          ? "danger"
                          : "foreground"
                      }
                      href="#"
                      size="lg"
                    >
                      {item}
                    </Link>
                  </NavbarMenuItem>
                ))}
              </NavbarMenu>
            </Navbar>
          
            <div className="bg-white  w-screen h-full justify-center items-center">
           
              {children}
              
            </div>
           
          </Providers>
        </div>
      </body>
    </html>
  );
}
